---
# tasks file for consul

- name: copy consul archive
  copy:
    src: files/consul_1.14.3_linux_amd64.zip
    dest: /tmp
  
- name: unzip
  unarchive:
    src: /tmp/consul_1.14.3_linux_amd64.zip
    dest: /usr/bin
    remote_src: true
    mode: a+x

- name: add consul user
  user:
    name: consul
    shell: /sbin/nologin
    system: true

- name: create consul folders
  file:
    path: "{{ item }}"
    state: directory
    mode: '0775'
    owner: consul
    group: consul
  loop:
    - /var/lib/consul
    - /etc/consul.d

- name: consul config
  template:
    src: config.json
    dest: /etc/consul.d/config.json
    owner: consul
    group: consul

- name: consul unit file
  template:
    src: consul.service
    dest: /lib/systemd/system/consul.service

- name: consul start
  systemd:
    name: consul.service
    state: started
    enabled: true
    daemon_reload: true
