---
# tasks file for consul

- name: copy consul archive
  copy:
    src: files/consul_1.14.3_linux_amd64.zip
    dest: /tmp
  
- name: unzip
  unarchive:
    src: /tmp/consul_1.14.3_linux_amd64.zip
    dest: /tmp

# - name: copy consul bin to /usr/local/bin
#   command: cp /tmp/consul_1.14.3_linux_amd64/consul /usr/local/bin && chmod a+x /usr/local/bin/consul

- name: copy consul bin to /usr/local/bin
  copy:
    src: /tmp/consul
    dest: /usr/local/bin/consul
    remote_src: true
    mode: a+x

- name: add consul user
  user:
    name: consul
    shell: /sbin/nologin
    system: true


